var files_dup =
[
    [ "appcommclient.cpp", "appcommclient_8cpp.html", "appcommclient_8cpp" ],
    [ "appcommclient.h", "appcommclient_8h.html", "appcommclient_8h" ],
    [ "appcommserver.cpp", "appcommserver_8cpp.html", "appcommserver_8cpp" ],
    [ "appcommserver.h", "appcommserver_8h.html", "appcommserver_8h" ],
    [ "appwritesdk.cpp", "appwritesdk_8cpp.html", null ],
    [ "appwritesdk.h", "appwritesdk_8h.html", "appwritesdk_8h" ],
    [ "errormodel.cpp", "errormodel_8cpp.html", "errormodel_8cpp" ],
    [ "errormodel.h", "errormodel_8h.html", "errormodel_8h" ],
    [ "garbagecollector.cpp", "garbagecollector_8cpp.html", null ],
    [ "garbagecollector.h", "garbagecollector_8h.html", "garbagecollector_8h" ],
    [ "membershipservice.cpp", "membershipservice_8cpp.html", null ],
    [ "membershipservice.h", "membershipservice_8h.html", "membershipservice_8h" ],
    [ "messageprocessor.cpp", "messageprocessor_8cpp.html", null ],
    [ "messageprocessor.h", "messageprocessor_8h.html", "messageprocessor_8h" ],
    [ "messagequeryservice.cpp", "messagequeryservice_8cpp.html", null ],
    [ "messagequeryservice.h", "messagequeryservice_8h.html", "messagequeryservice_8h" ],
    [ "model.cpp", "model_8cpp.html", null ],
    [ "model.h", "model_8h.html", "model_8h" ],
    [ "ratelimiter.cpp", "ratelimiter_8cpp.html", null ],
    [ "ratelimiter.h", "ratelimiter_8h.html", "ratelimiter_8h" ],
    [ "realtime.cpp", "realtime_8cpp.html", null ],
    [ "realtime.h", "realtime_8h_source.html", null ],
    [ "recentmessagecache.cpp", "recentmessagecache_8cpp.html", null ],
    [ "recentmessagecache.h", "recentmessagecache_8h.html", "recentmessagecache_8h" ],
    [ "recoverymanager.cpp", "recoverymanager_8cpp.html", null ],
    [ "recoverymanager.h", "recoverymanager_8h.html", "recoverymanager_8h" ],
    [ "state.h", "state_8h.html", "state_8h" ]
];